### ISSUE TITLE
Student и Project DAO

### ISSUE THREAD

**Issue by m-semibratov** [nceduc-mano-tlt-org/2018-school-journal#2]
Создать интерфейс DAO с CRUD методами, и реализовать in-momory имплементацию для классов Student и Project. Написать Unit-тесты для каждого метода.

**Comment by thirdmadman** [comment]
Не уверен что верно понял CRUD - сделал немного по другому.
Вместо интерфейса создал абстрактный класс, вероятно это ещё тоже будет обсуждаться.
Тесты доделаю чуть позже (когда пойму как правильно).
